# Generated by Django 3.0.7 on 2020-06-24 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerOlympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='Question-image/', verbose_name='Изображения вопроса')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=300, verbose_name='Ответ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
            },
        ),
        migrations.CreateModel(
            name='VariantOlympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.Category', verbose_name='Категория')),
                ('questions', models.ManyToManyField(to='variant.QuestionAnswerOlympiad', verbose_name='Вопросы варианта')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.CreateModel(
            name='UserResultOlympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.IntegerField(default=0, verbose_name='Количество правильных ответов')),
                ('time_start_olympiad', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время начала олимпиады')),
                ('end_start_olympiad', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время окончания олимпиады')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.VariantOlympiad', verbose_name='Вариант олимпиады')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат олимпиады',
                'verbose_name_plural': 'Результаты олимпиад',
            },
        ),
    ]
